language: objective-c
os: osx
osx_image: xcode8.3
script: xcodebuild clean test -project CCacheDemo.xcodeproj -scheme CCacheDemo -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3.1' -enableCodeCoverage YES | xcpretty
